name: Fetch ZeroDay Sheets

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch:     

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch Sheet 2 and save to data/sheet2.json
        run: |
          curl -sSL "https://opensheet.elk.sh/1lkNJ0uQwbeC1ZTRrxdtuPLCIl7mlUreoKfSIgajnSyY/2" -o data/sheet2.json

      - name: Fetch Sheet 3 and save to data/sheet3.json
        run: |
          curl -sSL "https://opensheet.elk.sh/1lkNJ0uQwbeC1ZTRrxdtuPLCIl7mlUreoKfSIgajnSyY/3" -o data/sheet3.json

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git commit -m "Update ZeroDay sheet data (daily)" || echo "No changes to commit"
          git push
